stages:
  - test
  - build

variables:
  DOCKER_HOST: tcp://docker:2375 
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

linter:
  stage: test
  image: node:16-alpine3.12 
  script:
    - npm i
    - npm run lint
    
build:
  stage: build
  image: docker:20.10.18-alpine3.16
  before_script:
      - echo ${CI_PASSWD} | docker login ${CI_REGISTRY} -u ${CI_USER} --password-stdin
  services:
      - name: docker:20.10.18-dind-alpine3.16
        alias: docker
        command: ["--insecure-registry=10.1.6.56:443"]
  script:
    - docker build .
      --tag ${CI_REGISTRY}/${CI_DOCKER_REPOSITORY}:${CI_COMMIT_SHORT_SHA}
    - docker push ${CI_REGISTRY}/${CI_DOCKER_REPOSITORY}:${CI_COMMIT_SHORT_SHA}
  only:
    - main
